inherit_gem:
  niftany: niftany_rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/support/data/**/*'

Metrics/ClassLength:
  Exclude:
  - 'app/services/symphony_client.rb'
  - 'app/models/patron.rb'
  - 'app/services/illiad_client.rb'

Metrics/BlockLength:
  Exclude:
  - 'config/environments/production.rb'
  - 'config/initializers/warden.rb'
  - 'spec/**/*'

Layout/LineLength:
  Exclude:
  - 'spec/factories/bibs.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'app/services/symphony_client.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/services/symphony_client_spec.rb'
    - 'spec/features/**/*'

RSpec/MessageChain:
  Exclude:
    - 'spec/models/patron_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/services/symphony_client_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/controllers/lending_policy_controller_spec.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/lending_policy_controller_spec.rb'
    - 'spec/features/holds_spec.rb'
    - 'spec/services/illiad_client_spec.rb' 

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/controllers/holds_controller_spec.rb'
    - 'spec/controllers/ill_controller_spec.rb'
    - 'spec/features/summaries_spec.rb'
    - 'spec/services/**/*'

Rails/I18nLocaleTexts:
  Exclude:
    - 'spec/views/shared/flash_msg.html.erb_spec.rb'
    - 'app/controllers/checkouts_controller.rb'

Style/HashSyntax:
  Exclude:
    - 'spec/helpers/holds_helper_spec.rb'
    - 'app/controllers/checkouts_controller.rb'

RSpec/Capybara/SpecificMatcher:
  Exclude:
    - 'spec/features/holds_spec.rb'
    - 'spec/views/holds/new.html.erb_spec.rb'
