inherit_gem:
  niftany: niftany_rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/support/data/**/*'

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/LineLength:
  Exclude:
  - 'spec/factories/bibs.rb'

Naming/AccessorMethodName:
  Exclude:
    - 'app/services/symphony_client.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/services/symphony_client_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/services/symphony_client_spec.rb'