dist: xenial
language: ruby
rvm:
  - 2.6.5
bundler_args: --without development
sudo: false
cache:
  bundler: true
  yarn: true
env:
  global:
    - RAILS_ENV=test
    - CC_TEST_REPORTER_ID=8f8554cdb6c9dd989fac690002e68f97075010f27f9fd9929dd87a8fc35587ac
addons:
  chrome: stable

before_install:
  - nvm install
  - gem update --system --force
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rails assets:precompile

script:
  - bundle exec niftany
  - yarn lint
  - bundle exec rake
  - yarn test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT