dist: xenial
language: ruby
rvm:
  - 2.6.5
bundler_args: --without development
sudo: false
cache:
  bundler: true
  yarn: true
env:
  global:
    - RAILS_ENV=test
addons:
  chrome: stable

before_install:
  - yes | gem update --system
  - gem install bundler
  - nvm install
  - gem update --system --force
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - bundle exec rails assets:precompile

script:
  - bundle exec niftany
  - bundle exec rake
