version: '3.5'
services:
  redis:
    image: redis:6.0.6-alpine3.12
    volumes:
      - redis-data:/data
    ports:
    - "6379:6379"
  test:
    depends_on:
      - redis
    profiles:
      - test
    command: ["sleep" ,"9999"]
    environment:
      SYMWS_URL: 'https://cat-stage.libraries.psu.edu:28443/symwsbc'
      SYMWS_USERNAME: 'myaccount'
      REDIS_SIDEKIQ_URI: "redis://redis:6379/1"
      RAILS_ENV: "test"
      REDIS_DATABASE_URI: "redis://redis:6379/2"
      SYMWS_PIN: "${SYMWS_PIN}"
    tty: true
    stdin_open: true
    build:
      context: .
      target: test
    volumes:
    - bundle-data:/app/vendor/bundle
    - node-data:/app/node_modules
    - type: bind
      source: ./
      target: /app/
  sidekiq:
    environment:
      SYMWS_URL: 'https://cat-stage.libraries.psu.edu:28443/symwsbc'
      SYMWS_USERNAME: 'myaccount'
      REDIS_SIDEKIQ_URI: "redis://redis:6379/1"
      RAILS_ENV: "development"
      REDIS_DATABASE_URI: "redis://redis:6379/2"
      SYMWS_PIN: "${SYMWS_PIN}"
    tty: true
    stdin_open: true
    build:
      context: .
      target: base
    volumes:
    - bundle-data:/app/vendor/bundle
    - node-data:/app/node_modules
    - type: bind
      source: ./
      target: /app/
    command: ["/app/bin/sidekiq"]
  web:
    environment:
      SYMWS_URL: 'https://cat-stage.libraries.psu.edu:28443/symwsbc'
      SYMWS_USERNAME: 'myaccount'
      REDIS_SIDEKIQ_URI: "redis://redis:6379/1"
      RAILS_ENV: "development"
      REDIS_DATABASE_URI: "redis://redis:6379/2"
      SYMWS_PIN: "${SYMWS_PIN}"
    tty: true
    stdin_open: true
    build:
      context: .
      target: base
    volumes:
    - bundle-data:/app/vendor/bundle
    - node-data:/app/node_modules
    - type: bind
      source: ./
      target: /app/
    ports:
      - "3000:3000"
volumes:
  redis-data:
  bundle-data:
  node-data:
