symws:
  webaccess_url:
  url:
  headers: {}
redis:
  sidekiq:
    uri: redis://127.0.0.1:6379/1
  database:
    uri: redis://127.0.0.1:6379/2
matomo_id: 11
pickup_locations:
  UP-PAT: 'Pattee Commons Services Desk'
  UP-ARCHIT: 'Architecture & Landscape Architecture Library, 111 Stuckeman'
  HERSHEY: 'College of Medicine (Hershey)'
  UP-MEDICAL: 'College of Medicine (University Park Program)'
  DSL-CARL: 'Dickinson Law (Carlisle)'
  DSL-UP: 'Penn State Law (UP)'
  UP-EMS: 'Earth & Min Sci Library 105 Deike'
  UP-ENGIN: 'Engineering Library 325 Hammond Building'
  UP-PAMS: 'Physical & Mathematical Sci Lib 201 Davey Lab'
  UP-OFFICE: 'University Park Faculty/Staff/Graduate Student Office Delivery'
  ABINGTON: 'Penn State Abington'
  ALTOONA: 'Penn State Altoona'
  BEAVER: 'Penn State Beaver'
  BEHREND: 'Penn State Erie'
  BERKS: 'Penn State Berks'
  BRANDYWINE: 'Penn State Brandywine'
  DUBOIS: 'Penn State Dubois'
  FAYETTE: 'Penn State Fayette'
  GREATVLY: 'Penn State Great Valley'
  GALLEGHENY: 'Penn State Greater Allegheny'
  HARRISBURG: 'Penn State Harrisburg'
  HAZLETON: 'Penn State Hazleton'
  LEHIGHVLY: 'Penn State Lehigh Valley'
  MONTALTO: 'Penn State Mont Alto'
  NEWKEN: 'Penn State New Kensington'
  SCHUYLKILL: 'Penn State Schuylkill'
  WSCRANTON: 'Penn State Scranton'
  SHENANGO: 'Penn State Shenango'
  WILKESBAR: 'Penn State Wilkes-Barre'
  YORK: 'Penn State York'
  WORLD: 'World Campus'
