symws:
  webaccess_url:
  url:
  headers: {}
home_page_flash_message_html:
redis:
  sidekiq:
    uri: <%= ENV.fetch 'REDIS_SIDEKIQ_URL', 'redis://127.0.0.1:6379/1' %>
  cache:
    uri: <%= ENV.fetch 'REDIS_URL', 'redis://127.0.0.1:6379/1' %>
  database:
    uri: <%= ENV.fetch 'REDIS_DATABASE_URL', 'redis://127.0.0.1:6379/1' %>