version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "monthly"
    default_assignees:
      - "banukutlu"
      - "whereismyjetpack"

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    default_assignees:
      - "banukutlu"
      - "whereismyjetpack"
