action_mailer:
  perform_deliveries: true
datadog:
  enabled: <%= ENV.fetch("DD_ENABELD", "true") %>
  environment: <%= ENV.fetch("DD_ENV", "production") %>
catalog:
  bulk_ris_url: 'http://catalog.libraries.psu.edu/bookmarks/bulk_ris/'